### ISSUE TITLE
Suggestion: Configuration using Crafttweaker

### ISSUE THREAD

**Issue by Guinaro** [Darkhax-Minecraft/AdditionalBanners#10]
Hey, I'm currently looking for a way to control which item creates which motif.
E.g. I want to use a TConstruct:shovel instead of an iron_shovel to create the shovel motif of the botania mod. (As I want to remove the normal tools from game, and force TConstruct to be used in my modpack)

Since you mentioned something about having a config file, maybe you could provide crafttweaker support instead.
Would you be interested in developing a Crafttweaker plugin that would allow us to:

- [ ] banners.addItems(IItemStack[]) Add banner recipes for items (which have an item representation)(Do not know if this can be done on the fly based on texture of the item or needs textures provided for the new motifs; which would imply some form of resources/textures management)

- [ ] banners.swapItem(IItemStack (old), (IItemstack (new)) (Alter the item used for a specific banner motif (like swap iron shovel with TConstruct Shovel)

- [ ] banners.removeItems(IItemStack[]) Remove banner recipes for certain items (so that we e.g. could provide those as quest rewards, but cannot be made!) (Based on input or maybe a name)

- [ ] Provide integration with the mod JustEnoughPatternBanners https://github.com/Lorexe/JustEnoughPatternBanners so that updates made by crafttweaker properly reflect in JEI?

- [ ] banners.motifs() as IItemStack[] A way to obtain a list of all banner motifs (aka input items)

- [ ] banners.removeAll() A quick and easy option to remove all possible banner designs

I think more functionality based on patterns, or banner stages, ... could be requested by others, but I think this would be a great base to start with.

Guinaro

**Comment by Darkhax** [comment]
I would like to do some stuff with CraftTweaker and banners, however the vanilla system is not very easily modified. I will keep this request in mind, but I can't make any promises.

**Comment by Guinaro** [comment]
For now I was able to recreate the recipes in a regular workbench. This way I at least can tweak the required ingredients as a few mods use the same item and thus only one recipe is usable.

For 2 recipe scripts recreating all the base recipes in a workbench see this gist.
https://gist.github.com/Guinaro/b357d6e90177290967b6693741503a7d

Ofcourse I'm still missing a way to add my own banners.

**Comment by Darkhax** [comment]
Creating new banner patterns is a bit out of scope for this mod. Potentially in another mod but no plans for this currently.
