### ISSUE TITLE
Crarting Impossible

### ISSUE THREAD

**Issue by Tokenyet** [Darkhax-Minecraft/AdditionalBanners#16]
Minecraft version: 1.13.2
Forge version: forge-1.13.2-25.0.99

I cannot create any banner. Are the tutorials on youtube  all outdated? I tried  AdditionalBanners-1.13.2-3.0.4.jar and AdditionalBanners-1.13.2-3.0.3.jar, but none of these worked. There is no crash, and I'm pretty sure It's loaded by forge in the startmenu forgelist.

If there is any infomation I needed to provide, please let me know.

**Comment by Tokenyet** [comment]
OK, I found out that I must provide color dye. Otherwise, It will never work. [This video](https://youtu.be/ymFUgqFWLZU) seems to outdated?

**Comment by vinnyg0621** [comment]
@Tokenyet what's crarting?
