### ISSUE TITLE
Asking for Repost Permission

### ISSUE THREAD

**Issue by P1nWheel0v0** [Darkhax-Minecraft/AdditionalBanners#17]
Hi, my name is PinWheel, I really like your mod. I wonder if I can repost this mod on MCBBS which is the largest Chinese Minecraft forum. Due to the barrier of language, most Chinese players are not able to play or even find this great mod. Thus I would like to introduce this mod to more Chinese players so that they can enjoy your mod as well. The entire repost will obey the rules list below and your own special requests.

- I will NOT take any credits of the mod and I will clearly state your official website (Curseforge and Github) at the head of my repost page.

- I will give the official download link directly and clearly note that "This is the official download link, please click here first"

- (Optional) In a case of the network firewalls (government policy stuff...) and network speed, I probably prepare another mirror link for backup. The mirror will direct to an Ad-free page (very like Dropbox).

- Last but not least, I will not use this mod to get profit/benefit in terms of money, etc... And I will clearly state that anyone who uses this mod must not use it to make money.

I will be really appreciated if you can give me permission.
Anyway, thank you for bringing us such an amazing mod and so much fun.

Yours sincerely,
PinWheel

**Comment by Darkhax** [comment]
Hello, 

I do not grant special or exclusive permissions to use my mods beyond the terms set by my license.
