### ISSUE TITLE
How do you make the Black Wolf banner pattern?

### ISSUE THREAD

**Issue by CaptainDarkwolf** [Darkhax-Minecraft/AdditionalBanners#19]
i wanted to add it to my banner but i can't find any way of doing it

**Comment by Darkhax** [comment]
This mod does not add a wolf pattern.

**Comment by CaptainDarkwolf** [comment]
Its listed on your mod when i look at my modpack, your mod is the only one
that adds banners

**Comment by Darkhax** [comment]
There is not, nor has there ever been a wolf pattern in this mod.
