### ISSUE TITLE
[Request] For the Wandering Trade

### ISSUE THREAD

**Issue by pwigary** [Darkhax-Minecraft/AdditionalBanners#22]
Could we potentially get an option to disable the wandering trades? Love everything else but want it to be more compactible with Endremaster which their wandering trader would sell an important item that don't want to be missed or occupied.

**Comment by Darkhax** [comment]
Thanks for the request. The latest [6.0.3](https://www.curseforge.com/minecraft/mc-mods/additional-banners/files/3279597) release will now have a wandering trader config file. You can disable all trades or tweak the individual trade values as needed.
