### ISSUE TITLE
A tale of WTF, and the resultant errors

### ISSUE THREAD

**Issue by Sunconure11** [Darkhax-Minecraft/AdditionalBanners#27]
I had been chasing errors down, since something kept killing my game before it could really start, and I have deduced the cause.

It is the hacky implementation of banners in Lightstones I was given, and it is fucking with your mod. However, the other guy working on the mod seems to be a bit busy with unrelated things, so I'd advise some stuff on your end for now.

https://github.com/Devan-Kerman/ARRP/issues/71

https://github.com/UltrusBot/missing-wilds/issues/1

https://github.com/Flemmli97/AdvancedGolems/issues/2

https://github.com/Paperdomo101/lightstones

**Comment by Sunconure11** [comment]
https://pastebin.com/Lw3kuXsq

**Comment by Darkhax** [comment]
This issue really has nothing to do with me or my mods and I am extremely short on time especially with 1.19 in a few days, so I can not go through all of these issues and help you fix them. I will reply to the lightstones issue with further information on how I am adding banner patterns, however there are broader unrelated issues with your mod that this won't fix.
