### ISSUE TITLE
Banner issue, in more depth [1.18.2]

### ISSUE THREAD

**Issue by Sunconure11** [Darkhax-Minecraft/AdditionalBanners#28]
After tracking down the source of the mixin error on 1.18.2 with Twilight Forest, the devs seem somewhat convinced this is something that needs to be fixed on your end, due to registering banners as early risers.

https://github.com/TeamTwilight/twilightforest-fabric/issues/81

**Comment by Darkhax** [comment]
I've fixed the rarity issue here https://github.com/Darkhax-Minecraft/AdditionalBanners/commit/f8d66e5f8123d7e4fde91504917e3436ac11db71. This seems like a separate issue to the one you were posting about previously though, as many of your crash logs did not even have Additional Banners installed.

**Comment by TheButterbrotMan** [comment]
When are you going to push that fix?

**Comment by Darkhax** [comment]
The fix was pushed 4 hours ago @TheButterbrotMan

**Comment by TheButterbrotMan** [comment]
> The fix was pushed 4 hours ago @TheButterbrotMan

Could you push that fix also for fabric 1.18.2 then, please?

**Comment by Darkhax** [comment]
@TheButterbrotMan It was pushed for Forge and Fabric 1.18.2 4 hours ago. 

https://www.curseforge.com/minecraft/mc-mods/additional-banners/files/3835685
