### ISSUE TITLE
[1.19.2] Incompatibility with Bedspread and Customizeable Elytra

### ISSUE THREAD

**Issue by Aulberon** [Darkhax-Minecraft/AdditionalBanners#33]
This mod seens to be incompatible with Bedspread and Customizable Elytra.
When present, we are no longer able to customize our elytras or beds.

It works normally in the stable versions, only alpha versions show this behavior.
[latest.log](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/9895851/latest.log)
[ModList.txt](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/9895852/ModList.txt)

**Comment by Darkhax** [comment]
Both the latest.log and ModList.txt file you have included do not contain AdditionalBanners at all. 

I created a new profile with only the latest versions of the mentioned mods and it works exactly as intended.
![image](https://user-images.githubusercontent.com/2250798/198889786-b30f1535-846b-477c-9473-11648171dcfd.png)
