### ISSUE TITLE
[1.19.2] Missing Banner Patern Textures (Conflict?)

### ISSUE THREAD

**Issue by Aulberon** [Darkhax-Minecraft/AdditionalBanners#34]
Textures don't show on banners.
The Alex's Mobs mod seems to have the same problem.

[latest.log](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/9895843/latest.log)
[ModList.txt](https://github.com/Darkhax-Minecraft/AdditionalBanners/files/9895844/ModList.txt)

![2022-10-30_09 50 54](https://user-images.githubusercontent.com/39103311/198879567-133f7313-bda7-48f0-acb1-ec6fbc471dbb.png)

**Comment by Darkhax** [comment]
Hello, this issue has popped up a few times now but unfortunately there is not a clear answer for players and nothing that can be done on my end to fix this issue. From what I understand, another unknown mod is unintentionally forcing the banner texture sheet to load before modded resources have loaded in. This means that any textures added after that unintentional load will not be correct.

https://github.com/AlexModGuy/AlexsMobs/issues/1145

**Comment by Aulberon** [comment]
Just an update, I've found the culprit. The mod Create Enchantment Industry.
If I take it out of the modlist, everything works as intended.

I've reported it to Create Industry Enchanchment issues page.
