### ISSUE TITLE
Banners acting... weird? (shaders vs. no shaders)

### ISSUE THREAD

**Issue by DEAFG0AT** [Darkhax-Minecraft/AdditionalBanners#38]
I tried using a /give code to give myself a banner and got this issue. I tried crafting it manually and had the same problem. Banners look fine without shaders, but with shaders are super glitchy, change as you look at them, and have different patterns on the front and back. It doesn't matter how many layers are on the banner, or which shader pack is in use. I'm running a few mods related to banners (Additional Banners, More Banner Features, and More Banner Layers), so I tried turning those off one by one, but that still didn't fix it.

Knowing Minecraft modding it's probably Geckolib or Iris fucking up the whole routine as usual but if there's a fix (or if it might be something else) please let me know! (I can send you a list of all the mods I'm using, but it's a LOT, and most of them wouldn't affect banners at all)

UPDATE: Just tried downgrading Iris, and it fixed the problem. I'm going to link this report to their page as well, but if there's any fix you can think of please share. Thanks

![2023-04-11_14 08 14](https://user-images.githubusercontent.com/104733108/231291476-72cb0b64-0748-48c8-a091-94f0bc1fb9ee.png)
![2023-04-11_14 09 48](https://user-images.githubusercontent.com/104733108/231291484-0aa31686-e72d-4637-9631-6e6bd9cbf2dd.png)
![2023-04-11_14 08 30](https://user-images.githubusercontent.com/104733108/231291537-aa07da73-dbd3-4324-9163-b969913b3336.png)
![2023-04-11_14 09 46](https://user-images.githubusercontent.com/104733108/231291553-754c7b5f-0875-494a-91ce-733728699d13.png)

**Comment by Darkhax** [comment]
Given that this happens with vanilla patterns as well, I don't think this mod has anything to do with the issue you're experiencing.
