### ISSUE TITLE
[BUG] Some patterns added by this mod seem to be incompatiable with the flags from Supplementaries

### ISSUE THREAD

**Issue by KelseySkybox** [Darkhax-Minecraft/AdditionalBanners#40]
### Minecraft Version

1.20.1 - Forge version 47.2.0

### Mod Version

Additional Banners 14.0.4 - Bookshelf 20.1.9 - Supplementaries 2.8.10 - Moonlight Lib 2.11.9

### Mod Loader

Forge

### What environment are you running the mod in?

Client

### Issue Description

Some (but not all) of the Additional Banners patterns- for example, including the Cobweb and excluding the Anchor- show up as a black and reddish checkerboard when applied to the flags added by the Supplementaries mod. (Please note that Supplementaries is currently still on 1.20.1, so I am using relatively-outdated 1.20.1 versions of Bookshelf and Additional Banners. However, I did not see any indication in the patch notes for later versions of Additional Banners, or on this GitHub bug tracker, that this issue was reported or fixed, so I decided to go ahead and report it anyway.)

I initially encountered this bug on a heavily modded world, but when I attempted to reproduce the issue on a new MultiMC launcher instance, with only the four mods in the "Mod Version" field installed, and no resource packs at all (not even the built-in Programmer Art), the same glitch occurred.

I know basically nothing about coding, so I don't know if Additional Banners or Supplementaries is causing the bug; but I plan to also report this glitch to the Supplementaries issue tracker.

Some screenshots I took of the issue are provided below.

![2024-04-02_00 18 44](https://github.com/Darkhax-Minecraft/AdditionalBanners/assets/138181427/fcd013ed-bc6a-4387-ad21-c0be9f877c69)
![2024-04-02_00 18 51](https://github.com/Darkhax-Minecraft/AdditionalBanners/assets/138181427/f317e1d4-e372-476a-aed9-980f6234dbb3)
![2024-04-02_00 18 53](https://github.com/Darkhax-Minecraft/AdditionalBanners/assets/138181427/2dccd536-861e-4b34-a296-36d0d01abd2e)

**Comment by Darkhax** [comment]
Hello, thanks for reporting this issue. It looks like Supplementaries adds support for Additional Banners on their end, so you should report this issue to them.
